### ISSUE TITLE
zodbupdate problem

### ISSUE THREAD

**Issue by oxygenius** [plone/zodbverify#14]
I have run zodbupdate on a recently migrated 5.1.6 to 5.2.1 Plone version (docker version with fixed python2)
I get 420 missing factories, but worse I get TypeError:

Warning: Missing factory for plone.dexterity.schema.generated SVDeStelling_0_File
Warning: Missing factory for Missing._Missing V
Warning: Missing factory for pytz _p
An error occured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/zodbupdate/main.py", line 223, in main
    updater()
  File "/usr/local/lib/python2.7/site-packages/zodbupdate/update.py", line 85, in __call__
    new = self.processor.rename(current)
  File "/usr/local/lib/python2.7/site-packages/zodbupdate/serialize.py", line 334, in rename
    data = unpickler.load()
TypeError: ('bad tzinfo state arg', <type 'datetime.datetime'>, ('\x07\xe6\x0b\x03\x14\x00\x00\x00\x00\x00', <broken pytz._p instance>))
Stopped processing, due to: ('bad tzinfo state arg', <type 'datetime.datetime'>, ('\x07\xe6\x0b\x03\x14\x00\x00\x00\x00\x00', <broken pytz._p instance>))
Traceback (most recent call last):
  File "/usr/local/bin/zodbupdate", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/zodbupdate/main.py", line 227, in main
    raise AssertionError()
AssertionError

Any ideas how I can continue to fix to be able to migrate to python3?

**Comment by ale-rt** [comment]
Uhm, the strange thing I see is that you are running `zodbupdate` with Python 2.7 instead of Python 3.

I am not sure the zodbupdate script was installed properly.
Did you install it with buildout or with pip?
That might explain the problem with the missing factories.
Among them I see you are missing the pytz one.
